aa: rand-m9-mstd0.5
amp: true
batch_size: 2
cutmix: 0.5
data_dir: horses_vs_zebras/data/
epochs: 20
mixup: 0.5
mixup_switch_prob: 0.30000000000000004
model: efficientnet_b0
num_classes: 2
output: horses_vs_zebras/models/trained-model-v1
